import type { TacticalInternalState, TacticalLogAlias } from "../types";

/** Canonical internal states used by risk / strike / coach pipelines */
export const TACTICAL_INTERNAL_STATES = [
  "TACTICAL_SWEEP_MICRO_EXEC",
  "SANTENMOKU_STRIKE",
  "R20_LOCKED",
  "R17_LOCKED",
  "SYSTEM_ROLLBACK",
  "ORDER_66_CANCEL_ALL",
  "INFINITY_GAUNTLET_ARMED",
  "MOSS_TINDER_LOCK",
  "SOIL_RESISTANCE_PASS",
  "SOIL_RESISTANCE_TRIP",
  "FLUX_SNAPSHOT_SAVED",
  "DONDON_4D_POCKET",
  "NEN_GYO_SENSING",
  "DOMAIN_EXPANSION_ZONE",
  "SHADOW_FLEET_ARISE",
  "NEN_ZETSU_CLOAK",
  "NEN_VOW_LIMITATION",
  "AFTERIMAGE_FLEET",
  "IMBALANCE_RADAR_ACTIVE",
  "DYNAMIC_SL_ENFORCED",
  "ANTI_MEV_SHIELD",
  "TRUTH_GATE_AUDIT",
  "DONDUM_HUD_ACTIVE",
  "SYSTEM_STATE_STABLE",
  "FLEET_HEALTH_CHECK",
] as const satisfies readonly TacticalInternalState[];

/**
 * Primary alias per internal state — canonical default for structured logs.
 * Optional alternates live in TACTICAL_OPTIONAL_ALIASES (same underlying guard).
 */
export const TACTICAL_STATE_ALIASES: Readonly<
  Record<TacticalInternalState, TacticalLogAlias>
> = {
  TACTICAL_SWEEP_MICRO_EXEC: "TACTICAL_SWEEP_NO_FORM_STRIKE",
  SANTENMOKU_STRIKE: "FLURRY_RUSH_STRIKE",
  R20_LOCKED: "R20_LOCKED",
  R17_LOCKED: "R17_LOCKED",
  SYSTEM_ROLLBACK: "FLUX_SNAPSHOT_RESTORED",
  ORDER_66_CANCEL_ALL: "ORDER_66_TRIGGERED",
  INFINITY_GAUNTLET_ARMED: "INFINITY_GAUNTLET_ARMED",
  MOSS_TINDER_LOCK: "MOSS_TINDER_LOCK",
  SOIL_RESISTANCE_PASS: "INFINITY_GAUNTLET_ARMED",
  SOIL_RESISTANCE_TRIP: "POWER_GEM_TRIPPED",
  FLUX_SNAPSHOT_SAVED: "FLUX_SNAPSHOT_SAVED",
  DONDON_4D_POCKET: "DONDON_4D_POCKET_ACTIVE",
  NEN_GYO_SENSING: "NEN_GYO_SENSING",
  DOMAIN_EXPANSION_ZONE: "DOMAIN_EXPANSION_SOIL",
  SHADOW_FLEET_ARISE: "SHADOW_ARRAISE_FLEET",
  NEN_ZETSU_CLOAK: "NEN_ZETSU_CLOAK",
  NEN_VOW_LIMITATION: "NEN_VOW_LIMITATION",
  AFTERIMAGE_FLEET: "AFTERIMAGE_FLEET_DECOY",
  IMBALANCE_RADAR_ACTIVE: "EIGHT_FORMATIONS_SCAN",
  DYNAMIC_SL_ENFORCED: "TEN_COMMANDMENTS_SL",
  ANTI_MEV_SHIELD: "TURTLE_SHIP_PROTECT",
  TRUTH_GATE_AUDIT: "GATE_OF_TRUTH_EQUAL_EXCHANGE",
  DONDUM_HUD_ACTIVE: "DONDUM_MARKET_OVERVIEW",
  SYSTEM_STATE_STABLE: "SYSTEM_STATE_STABLE",
  FLEET_HEALTH_CHECK: "FLEET_HEALTH_CHECK",
};

/**
 * Optional annotation aliases — each maps to an existing internal state.
 * Active when `TACTICAL_LOG_METAPHORS=true` via resolveTacticalAlias(state, variant).
 */
export const TACTICAL_OPTIONAL_ALIASES: Readonly<
  Partial<Record<TacticalInternalState, readonly TacticalLogAlias[]>>
> = {
  R20_LOCKED: [
    "HIGH_VOLATILITY_GUARD_MOUNTAIN",
    "DIAMOND_BODY_LOCK",
    "POTTER_INVISIBILITY_CLOAK",
    "OVERCOOKED_FIRE_EXTINGUISHER",
    "ZIWEI_MUTATION_RISK_SHIELD",
    "NUWA_FIVE_COLOR_REPAIR",
    "HAWKING_SINGULARITY_LOCK",
    "BOTTOMLINE_RISK_PREVENTION",
  ],
  SANTENMOKU_STRIKE: ["DUGU_NINE_SWORDS_STRIKE", "HIGH_VOLATILITY_GUARD_WIND"],
  TACTICAL_SWEEP_MICRO_EXEC: ["EQUILIBRIUM_REST_IMPERMANENCE_GUARD", "HIGH_VOLATILITY_GUARD_FIRE"],
  SOIL_RESISTANCE_PASS: ["HIGH_VOLATILITY_GUARD_FOREST"],
  SOIL_RESISTANCE_TRIP: [
    "NOAH_ARK_PROTECT",
    "ARK_SAFETY_PROTOCOL",
    "JIUYANG_IMPACT_ABSORB",
    "FOMO_MARKET_NOISE_MUTED",
    "JOBS_SAY_NO_TO_FOMO",
    "SHAKESPEARE_TO_BE_GATE",
    "DISC_COMPLIANCE_EXECUTION",
    "DINOSAUR_KT_EXTINCTION_SHIELD",
    "QUANTUM_TUNNELING_VOLATILITY_TRIP",
  ],
  IMBALANCE_RADAR_ACTIVE: [
    "EIGHT_FORMATIONS_MATRIX",
    "PARADIGM_SHIFT_EDGE_SYNC",
    "INVISIBLE_HAND_EQUILIBRIUM",
    "HUMAN_DESIGN_AUTHORITY_GATE",
    "HOHMANN_TRANSFER_WINDOW_EXEC",
    "CAPITAL_EFFICIENCY_STRIKE",
    "FENCING_MICROSECOND_REACTION_STRIKE",
  ],
  NEN_VOW_LIMITATION: ["TEN_COMMANDMENTS_SL"],
  DYNAMIC_SL_ENFORCED: [
    "NEN_VOW_LIMITATION",
    "GENESIS_ANCHOR_COVENANT",
    "POTTER_UNBREAKABLE_VOW",
    "LUBAN_RULER_BOUNDS_CHECK",
    "ATLANTIS_ORICHALCUM_SHIELD",
    "FRACTIONAL_KELLY_CAPITAL_SIZING",
  ],
  SHADOW_FLEET_ARISE: ["SEVEN_STARS_FLEET"],
  AFTERIMAGE_FLEET: ["EMPTY_FORT_DECOY"],
  MOSS_TINDER_LOCK: ["TURTLE_SHIP_SHIELD"],
  ANTI_MEV_SHIELD: [
    "MOSS_TINDER_LOCK",
    "MJ_MOONWALK_ANTI_SLIPPAGE",
    "COMMONS_PROTECTION_ACTIVE",
    "NASH_EQUILIBRIUM_MEV_COUNTER",
  ],
  SYSTEM_STATE_STABLE: [
    "SANTENMOKU_DYNAMIC_TENSION",
    "RICH_DAD_ASSET_CASHFLOW",
    "LUBAN_MORTISE_TENON_LOCK",
    "FIVE_ELEMENTS_EQUILIBRIUM",
    "ICHING_DYNAMIC_PHASE_CONTROL",
    "SCHRODINGER_WAVE_STATE_COLLAPSE",
  ],
  FLEET_HEALTH_CHECK: ["BYZANTINE_FLEET_CONSENSUS", "TIEBAN_NUMERICAL_PRECISION"],
  TRUTH_GATE_AUDIT: [
    "CYPHERPUNK_MANIFESTO_SHIELD",
    "MONEY_AND_YOU_INTEGRITY",
    "MBTI_INTJ_ARCHITECT_LOGIC",
    "INCA_QUIPU_IMMUTABLE_LOG",
  ],
};
